# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(1018, 768)
        self.centralwidget = QtWidgets.QWidget(MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(930, 690, 75, 23))
        self.exitBtn.setObjectName("exitBtn")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(830, 690, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1011, 681))
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1011, 661))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 0, 255))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 1011, 651))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(21)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(20, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 1011, 661))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 1011, 661))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(0)
        self.tableWidget_7.setRowCount(0)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_8.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(0)
        self.tableWidget_8.setRowCount(0)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_9.setGeometry(QtCore.QRect(10, 0, 781, 481))
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(0)
        self.tableWidget_9.setRowCount(0)
        self.tabWidget.addTab(self.tab_9, "")
        MainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 26))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menusss = QtWidgets.QMenu(self.menubar)
        self.menusss.setObjectName("menusss")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)
        self.actionaaa = QtWidgets.QAction(MainWin)
        self.actionaaa.setObjectName("actionaaa")
        self.actionbbb = QtWidgets.QAction(MainWin)
        self.actionbbb.setObjectName("actionbbb")
        self.actionccc = QtWidgets.QAction(MainWin)
        self.actionccc.setObjectName("actionccc")
        self.actionquit = QtWidgets.QAction(MainWin)
        self.actionquit.setObjectName("actionquit")
        self.actionHelp = QtWidgets.QAction(MainWin)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWin)
        self.actionAbout.setObjectName("actionAbout")
        self.menusss.addAction(self.actionaaa)
        self.menusss.addAction(self.actionbbb)
        self.menusss.addAction(self.actionccc)
        self.menusss.addAction(self.actionquit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menusss.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWin)
        self.tabWidget.setCurrentIndex(0)
        self.exitBtn.clicked.connect(MainWin.close)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "电力设备履历录入系统"))
        self.exitBtn.setText(_translate("MainWin", "退出"))
        self.pushButton.setText(_translate("MainWin", "保存"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWin", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWin", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWin", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWin", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWin", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWin", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWin", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWin", "8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWin", "年度"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWin", "概况记录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWin", "历史概况"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWin", "顺号"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWin", "项目名称"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWin", "单位"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWin", "2001年"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWin", "2002年"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWin", "2003年"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWin", "2004年"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWin", "2005年"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWin", "2006年"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWin", "2007年"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWin", "2008年"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWin", "2009年"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWin", "2010年"))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWin", "2011年"))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWin", "2012年"))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWin", "2013年"))
        item = self.tableWidget_2.horizontalHeaderItem(16)
        item.setText(_translate("MainWin", "2014年"))
        item = self.tableWidget_2.horizontalHeaderItem(17)
        item.setText(_translate("MainWin", "2015年"))
        item = self.tableWidget_2.horizontalHeaderItem(18)
        item.setText(_translate("MainWin", "2016年"))
        item = self.tableWidget_2.horizontalHeaderItem(19)
        item.setText(_translate("MainWin", "2017年"))
        item = self.tableWidget_2.horizontalHeaderItem(20)
        item.setText(_translate("MainWin", "2018年"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWin", "设备概况表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWin", "设备汇总表 (设备变更履历表)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWin", "分段"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWin", "分相"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWin", "隔开"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWin", "跨越"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWin", "桥梁"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWin", "上网点"))
        self.menusss.setTitle(_translate("MainWin", "File"))
        self.menuHelp.setTitle(_translate("MainWin", "Help"))
        self.actionaaa.setText(_translate("MainWin", "open"))
        self.actionbbb.setText(_translate("MainWin", "save"))
        self.actionccc.setText(_translate("MainWin", "close"))
        self.actionquit.setText(_translate("MainWin", "quit"))
        self.actionHelp.setText(_translate("MainWin", "Help"))
        self.actionAbout.setText(_translate("MainWin", "About"))

