# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\swallow\learngit\TestUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(560, 500, 75, 23))
        self.exitBtn.setObjectName("exitBtn")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 500, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 471, 481))
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 371, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.tab)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(10, 340, 371, 16))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.tab)
        self.verticalScrollBar.setGeometry(QtCore.QRect(390, 10, 16, 321))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        MainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 23))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menusss = QtWidgets.QMenu(self.menubar)
        self.menusss.setObjectName("menusss")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)
        self.actionaaa = QtWidgets.QAction(MainWin)
        self.actionaaa.setObjectName("actionaaa")
        self.actionbbb = QtWidgets.QAction(MainWin)
        self.actionbbb.setObjectName("actionbbb")
        self.actionccc = QtWidgets.QAction(MainWin)
        self.actionccc.setObjectName("actionccc")
        self.actionquit = QtWidgets.QAction(MainWin)
        self.actionquit.setObjectName("actionquit")
        self.actionHelp = QtWidgets.QAction(MainWin)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWin)
        self.actionAbout.setObjectName("actionAbout")
        self.menusss.addAction(self.actionaaa)
        self.menusss.addAction(self.actionbbb)
        self.menusss.addAction(self.actionccc)
        self.menusss.addAction(self.actionquit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menusss.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWin)
        self.tabWidget.setCurrentIndex(0)
        self.exitBtn.clicked.connect(MainWin.close)
        self.pushButton.clicked.connect(MainWin.showFullScreen)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "电力设备履历录入系统"))
        self.exitBtn.setText(_translate("MainWin", "退出"))
        self.pushButton.setText(_translate("MainWin", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWin", "表格一"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWin", "表格二"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWin", "表格三"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWin", "表格四"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWin", "表格五"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWin", "表格6"))
        self.menusss.setTitle(_translate("MainWin", "File"))
        self.menuHelp.setTitle(_translate("MainWin", "Help"))
        self.actionaaa.setText(_translate("MainWin", "open"))
        self.actionbbb.setText(_translate("MainWin", "save"))
        self.actionccc.setText(_translate("MainWin", "close"))
        self.actionquit.setText(_translate("MainWin", "quit"))
        self.actionHelp.setText(_translate("MainWin", "Help"))
        self.actionAbout.setText(_translate("MainWin", "About"))

