# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Desk\Documents\GitHub\learngit\TestUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(940, 680, 75, 23))
        self.exitBtn.setObjectName("exitBtn")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 680, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1011, 681))
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(17)#17
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(0)
        self.tableWidget_7.setRowCount(0)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_8.setGeometry(QtCore.QRect(0, 0, 781, 481))
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(0)
        self.tableWidget_8.setRowCount(0)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_9.setGeometry(QtCore.QRect(10, 0, 781, 481))
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(0)
        self.tableWidget_9.setRowCount(0)
        self.tabWidget.addTab(self.tab_9, "")
        MainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menusss = QtWidgets.QMenu(self.menubar)
        self.menusss.setObjectName("menusss")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)
        self.actionaaa = QtWidgets.QAction(MainWin)
        self.actionaaa.setObjectName("actionaaa")
        self.actionbbb = QtWidgets.QAction(MainWin)
        self.actionbbb.setObjectName("actionbbb")
        self.actionccc = QtWidgets.QAction(MainWin)
        self.actionccc.setObjectName("actionccc")
        self.actionquit = QtWidgets.QAction(MainWin)
        self.actionquit.setObjectName("actionquit")
        self.actionHelp = QtWidgets.QAction(MainWin)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWin)
        self.actionAbout.setObjectName("actionAbout")
        self.menusss.addAction(self.actionaaa)
        self.menusss.addAction(self.actionbbb)
        self.menusss.addAction(self.actionccc)
        self.menusss.addAction(self.actionquit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menusss.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWin)
        self.tabWidget.setCurrentIndex(0)
        self.exitBtn.clicked.connect(MainWin.close)
        # self.pushButton.clicked.connect(MainWin.showFullScreen)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "电力设备履历录入系统"))
        self.exitBtn.setText(_translate("MainWin", "退出"))
        self.pushButton.setText(_translate("MainWin", "OK"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWin", "2001"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWin", "2002"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWin", "2003"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWin", "2004"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWin", "2005"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWin", "2006"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWin", "2007"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWin", "2008"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWin", "2009"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWin", "2010"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWin", "2011"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWin", "2012"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWin", "2013"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWin", "2014"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWin", "New Row"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWin", "2016"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWin", "2017"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWin", "年度"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWin", "概况记录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWin", "历史概况"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWin", "设备概况表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWin", "设备汇总表 (设备变更履历表)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWin", "分段"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWin", "分相"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWin", "隔开"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWin", "跨越"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWin", "桥梁"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWin", "上网点"))
        self.menusss.setTitle(_translate("MainWin", "File"))
        self.menuHelp.setTitle(_translate("MainWin", "Help"))
        self.actionaaa.setText(_translate("MainWin", "open"))
        self.actionbbb.setText(_translate("MainWin", "save"))
        self.actionccc.setText(_translate("MainWin", "close"))
        self.actionquit.setText(_translate("MainWin", "quit"))
        self.actionHelp.setText(_translate("MainWin", "Help"))
        self.actionAbout.setText(_translate("MainWin", "About"))

